server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test02
    username: root
    password: sapassword
  devtools:
    restart:
      poll-interval: 2s
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true